spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://b00f679f1f391f:9dd13396@us-cdbr-east-06.cleardb.net/heroku_9e90639e44a4709?reconnect=true
    username: b00f679f1f391f
    password: 9dd13396
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: ${port:8080}
